version: '3.8'

services:
  api:
    # Constrói a imagem a partir do Dockerfile no diretório atual (.)
    # (Opcional) Define um nome fixo para o contêiner para fácil identificação
    container_name: api
    build: .
    # Mapeia a porta 8000 do seu computador (host) para a porta 8000 do contêiner
    ports:
      - "8000:8000"
    # Define variáveis de ambiente para o contêiner.
    # É uma boa prática para gerenciar configurações, como conexões de banco de dados.
    environment:
      # Esta variável será lida pelo database.py para configurar a URL do banco de dados.
      - DATABASE_URL=sqlite:////app/escola.db
      # Força o Python a enviar a saída diretamente para o terminal sem buffer,
      # garantindo que os logs apareçam em tempo real.
      - PYTHONUNBUFFERED=1
      # Impede o Python de criar arquivos .pyc, mantendo o sistema de arquivos limpo.
      - PYTHONDONTWRITEBYTECODE=1
    # Monta o diretório atual no contêiner para desenvolvimento e persistência de dados
    volumes:
      - .:/app
    # Comando para iniciar a aplicação com hot-reload, permitindo que o servidor reinicie automaticamente com as alterações no código
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload